### ISSUE TITLE
cannot import name 'Associator' from 'quadricslam'

### ISSUE THREAD

**Issue by yutongwangBIT** [qcr/quadricslam#1]
Hi, 

thanks for releasing your code.

After installing using `pip install quadricslam`  I tried to run `from quadricslam import DataSource, Detector, Associator, visualise`, and then got the error `ImportError: cannot import name 'Associator' from 'quadricslam'` . I am wondering why and I'd be grateful for your help.

**Comment by btalb** [comment]
Thanks for your enthusiasm @yutongwangBIT .

This is very much under active development. There are big changes on the [develop branch](https://github.com/qcr/quadricslam/tree/develop) that will hopefully make into a release later this week.

If you're looking to use before the next release I'd recommend:
1. Cloning the develop branch locally
2. Installing the local copy as shown in #2

**Comment by btalb** [comment]
Resolved with the release of [v1.0.0](https://github.com/qcr/quadricslam/releases/tag/v1.0.0).
